[project]
name = "wp_export2yaml"
version = "0.1.0"
description = "An utility to convert WordPress WXR (XML export) files into clean, readable YAML files"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lxml>=5.4.0",
    "pyyaml>=6.0.2",
]
